
#importonce

SPRITES: {
  .label FIRST_SPRITE_PTR = ((Sprites - IntroMap) / 64)
  .label PLAYER_STAND_L0 = FIRST_SPRITE_PTR
  .label PLAYER_STAND_L1_RIGHT = FIRST_SPRITE_PTR + 1
  .label PLAYER_STAND_L1_LEFT = FIRST_SPRITE_PTR + 2

  .label PLAYER_WALKDOWN_STEP1_L0 = FIRST_SPRITE_PTR + 3
  .label PLAYER_WALKDOWN_STEP1_L1_RIGHT = FIRST_SPRITE_PTR + 4
  .label PLAYER_WALKDOWN_STEP1_L1_LEFT = FIRST_SPRITE_PTR + 5

  .label PLAYER_WALKDOWN_STEP2_L0 = FIRST_SPRITE_PTR + 6
  .label PLAYER_WALKDOWN_STEP2_L1_RIGHT = FIRST_SPRITE_PTR + 7
  .label PLAYER_WALKDOWN_STEP2_L1_LEFT = FIRST_SPRITE_PTR + 8

  .label SPRITES_0 = Level1 + $3f8
  .label SPRITES_1 = SPRITES_0 + 1

}

#import "_allimport.asm"
